name       : ibus-libpinyin
version    : 1.11.1
release    : 7
source     :
    - https://github.com/libpinyin/ibus-libpinyin/archive/1.11.1.tar.gz : a30d5cd15920c669df296593ffd9747f07faeb0edf752bc83ebf8a5db608ea76
license    : GPL-2.0
component  : desktop.core
summary    : Intelligent Pinyin engine based on libpinyin for IBus
description: |
    Intelligent Pinyin engine based on libpinyin for IBus
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libpinyin)
    - pkgconfig(lua-5.1)
    - pkgconfig(sqlite3)
    - gnome-common
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
