name       : ibus-libpinyin
version    : 1.10.0
release    : 6
source     :
    - https://github.com/libpinyin/ibus-libpinyin/releases/download/1.10.0/ibus-libpinyin-1.10.0.tar.gz : 6cc4f80d2348f93ed408d52fb33b45736f51ae33335a869e8a3bb6460957087b
license    : GPL-2.0
component  : desktop.core
summary    : Intelligent Pinyin engine based on libpinyin for IBus
description: |
    Intelligent Pinyin engine based on libpinyin for IBus
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libpinyin)
    - pkgconfig(lua-5.1)
    - pkgconfig(sqlite3)
    - gnome-common
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
