name       : ibus-libpinyin
version    : 1.9.0
release    : 5
source     :
    - https://github.com/libpinyin/ibus-libpinyin/archive/1.9.0.tar.gz : c8ec2450cec6f11870982b0130293dc967632631077029ca76c27ef349189e3e
license    : GPL-2.0
component  : desktop.core
summary    : Intelligent Pinyin engine based on libpinyin for IBus
description: |
    Intelligent Pinyin engine based on libpinyin for IBus
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libpinyin)
    - pkgconfig(lua-5.1)
    - pkgconfig(sqlite3)
    - gnome-common
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
